Use module path aliases for imports
sourcegraph/learn pull request #156
Opened 2021-08-10 18:03 UTC by katjuell

### What should this PR do?
Resolves [DEVED-92](https://sourcegraph.atlassian.net/browse/DEVED-92) by adding module path aliases for imports.

Also implements `MarkdownFileWithUrl` as an interface rather than type.

### Why are we making this change?
Nested imports often lead to confusion and a less-than-ideal reading experience. Aliases prevent this by making our code easier to read and reason about.

### What are the acceptance criteria? 
- The app works as it currently does on prod, and the decisions in the PR make sense.

### How should this PR be tested?
- Check out the branch and ensure that everything behaves as expected.

## Pull request process

**Reviewers**:

1. Test functionality using the criteria above.
2. Offer tips for efficiency, feedback on best practices, and possible alternative approaches and things that may not have been considered.
3. For shorter, "quick" PRs, use your best judgement on #​2.
4. Use a collaborative approach and provide resources and/or context where appropriate.
5. Provide screenshots/grabs where appropriate to show findings during review.

**Reviewees**:

1. Prefer incremental and appropriately-scoped changes.
2. Leave a comment on things you want explicit feedback on.
3. Respond clearly to comments and questions.

2021-08-10 18:04 UTC, katjuell commented on components/atoms/CreativeCommonsNotice/index.tsx
> +                target="_blank"
This isn't related to this PR, but was something I meant to wrap up in the CSS reorg.

2021-08-10 18:04 UTC, katjuell commented on components/atoms/CreativeCommonsNotice/index.tsx
> +            target="_blank"
Same as above.

2021-08-11 00:19 UTC, ltagliaferri requested changes
This is cleaner than the relative paths and makes good use of TypeScript's path mapping. Everything working as expected, thanks!

2021-08-11 00:20 UTC, ltagliaferri approved these changes

2021-08-11 00:20 UTC, ltagliaferri commented
> This is cleaner than the relative paths and makes good use of TypeScript's path mapping. Everything working as expected, thanks!

Sorry, I pressed "request changes" instead of "approve changes" :doh:

2021-08-11 00:21 UTC, merged